name: Deploy to AWS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Deploy website to S3
      run: |
        aws s3 sync ./chef-website-template s3://k21-cloud-resume-challenge/chef-website-template --delete
    
    - name: Deploy Lambda function
      run: |
        zip function.zip lambda_function.py
        aws lambda update-function-code --function-name cloud-resume-challenge --zip-file fileb://function.zip
    
    - name: Invalidate CloudFront
      run: |
        aws cloudfront create-invalidation --distribution-id E1KPHFE6PQNOJT --paths "/*"



